name: Check if ColorStack Member

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  pr_comment:
    name: Comment on Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: apps/admin-dashboard/app/shared/queries

      - name: Cache Turborepo setup
        uses: actions/cache@v4
        with:
          # When running turbo commands, we use `.turbo` as the cache directory.
          # See the root `package.json` for reference.
          path: .turbo

          key: ${{ runner.os }}-turbo-${{ github.sha }}

          # This is how GitHub Actions restores the cache. Because we only
          # the prefix of the key (and not the `github.sha`), this will allow
          # us to hit the cache on any CI runs on commit on any branch.
          restore-keys: |
            ${{ runner.os }}-turbo-
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - run: npm run build # Compile TypeScript files
      - uses: actions/github-script@v4
        with:
          script: |
            const script = await import('${{ github.workspace }}/apps/admin-dashboard/app/shared/queries/check_member.js');
            const userExists = await script.StudentHasGithub(githubId);

            if (userExists) {
              github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `It doesn\'t seem like you are a ColorStack member. This codebase is primarily meant to benefit our students so that they can gain experience contributing to a codebase, so unfortunately your contribution will not be prioritized. 
                
            If you are a ColorStack member, then be sure to connect your GitHub account in your [Member Profile](https://app.colorstack.io/profile/integrations)!`
              });
            }
