name: Check if ColorStack Member

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  pr_comment:
    name: Comment on Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR
        uses: actions/github-script@v4
        with:
          script: |
            const script = require('check_member.js')
            script({github, context})

